/**
 * 造境 ZaoJing — 热门电影数据层 v1.0
 * 包含：电影数据结构 + 10 部本地 fallback 电影 + 热度等级定义
 */

// 热度等级定义
export const HEAT_LEVELS = {
  explosive: { label: '社交爆表', color: '#e74c3c', min: 90 },
  high: { label: '高热', color: '#e67e22', min: 70 },
  medium: { label: '上升', color: '#f1c40f', min: 50 },
  rising: { label: '新晋', color: '#3498db', min: 0 },
};

// 根据热度分数获取热度等级
export function getHeatLevel(score) {
  if (score >= HEAT_LEVELS.explosive.min) return 'explosive';
  if (score >= HEAT_LEVELS.high.min) return 'high';
  if (score >= HEAT_LEVELS.medium.min) return 'medium';
  return 'rising';
}

// 10 部本地 fallback 电影数据（2026 年 6 月热门）
export const FALLBACK_MOVIES = [
  {
    id: 'nezha2-2025',
    title: '哪吒之魔童闹海',
    enTitle: 'Ne Zha 2',
    director: '饺子',
    releaseDate: '2025-01-29',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bTMf8M7rZ21fChGdtsZtJj4Dfqh.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/zxi6WQPVc0uQAG5TtLsKvxYHApC.jpg',
    heatScore: 95,
    boxOffice: 16400000000,
    boxOfficeRank: 1,
    socialHeat: 'explosive',
    socialMentions: 12000000,
    trendingPeriod: '2025.01 - 2025.06',
    lastUpdated: '2026-06-24',
    visualStyle: '东方水墨神话史诗',
    styleKeywords: ['水墨', '高饱和', '神话', '东方色彩', '史诗'],
    signatureScenes: ['哪吒与敖丙的宿命对决', '混元珠爆发', '海底龙宫崩塌'],
    iconicQuotes: ['我命由我不由天', '若命运不公，就和它斗到底'],
    styleDNA: {
      colorTemperature: 'warm',
      saturation: 'high',
      contrast: 'high',
      compositionType: 'dynamic',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'painterly',
    },
    colors: {
      primary: '#c0392b',
      secondary: '#2c3e50',
      accent: '#f39c12',
      bg: '#1a0a0a',
      text: '#f5e6d3',
      textLight: '#c9a96e',
    },
    matchedDirectorIds: ['lee', 'kurosawa', 'miyazaki'],
    matchScores: { lee: 0.85, kurosawa: 0.78, miyazaki: 0.65 },
    stylePrompt:
      'Eastern ink wash mythology epic, high saturation traditional Chinese colors, dramatic lighting, monumental scale, dynamic composition with flowing ink elements, mythological atmosphere',
    negativePrompt: 'low quality, blurry, text, watermark, deformed, western style',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 900,
    status: 'active',
    featured: true,
    approved: true,
  },
  {
    id: 'toy5-2026',
    title: '玩具总动员5',
    enTitle: 'Toy Story 5',
    director: '安德鲁·斯坦顿',
    releaseDate: '2026-06-19',
    posterUrl: 'https://image.tmdb.org/t/p/w500/l9ui7Irttuekt4CMTOmyAMIDsQI.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/qjTqY5coNiz6sVtPng40IzltsoN.jpg',
    heatScore: 88,
    boxOffice: 131000000,
    boxOfficeRank: 2,
    socialHeat: 'high',
    socialMentions: 11620000,
    trendingPeriod: '2026.06',
    lastUpdated: '2026-06-24',
    visualStyle: '皮克斯3D动画·温暖怀旧',
    styleKeywords: ['3D动画', '温暖', '怀旧', '玩具', '微缩视角'],
    signatureScenes: ['胡迪与巴斯光年重聚', '玩具天团合体'],
    iconicQuotes: ['飞向宇宙，浩瀚无垠', '你是我最好的朋友'],
    styleDNA: {
      colorTemperature: 'warm',
      saturation: 'medium',
      contrast: 'medium',
      compositionType: 'symmetric',
      lightingType: 'natural',
      scale: 'intimate',
      pace: 'dynamic',
      texture: 'smooth',
    },
    colors: {
      primary: '#d4a843',
      secondary: '#8b6914',
      accent: '#c0392b',
      bg: '#2d1f0f',
      text: '#f0e0c0',
      textLight: '#c9a96e',
    },
    matchedDirectorIds: ['wes', 'miyazaki', 'lee'],
    matchScores: { wes: 0.82, miyazaki: 0.75, lee: 0.6 },
    stylePrompt:
      'Pixar 3D animation style, warm nostalgic tones, toy miniature perspective, soft natural lighting, symmetrical composition, playful and heartwarming',
    negativePrompt: 'dark mood, horror, realistic photo, grainy',
    fontFamily: "'Noto Sans SC', sans-serif",
    titleWeight: 800,
    status: 'active',
    featured: false,
    approved: true,
  },
  {
    id: 'avatar3-2025',
    title: '阿凡达3：火与烬',
    enTitle: 'Avatar: Fire and Ash',
    director: '詹姆斯·卡梅隆',
    releaseDate: '2025-12-19',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5jW601WKpT1yTwWsJcYvUwl8cB.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
    heatScore: 82,
    boxOffice: 8500000000,
    boxOfficeRank: 3,
    socialHeat: 'high',
    socialMentions: 8560000,
    trendingPeriod: '2025.12 - 2026.03',
    lastUpdated: '2026-06-24',
    visualStyle: '潘多拉海洋·生物荧光美学',
    styleKeywords: ['生物荧光', '海洋', '科幻', '3D', '异星'],
    signatureScenes: ['阿凡达半边脸特写', '潘多拉海洋生态奇观'],
    iconicQuotes: ['我看到你了', '一切能量都是借来的，终有一天要归还'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'high',
      contrast: 'high',
      compositionType: 'centered',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'smooth',
    },
    colors: {
      primary: '#00a8cc',
      secondary: '#001f3f',
      accent: '#7fffd4',
      bg: '#0a0a2a',
      text: '#e0f0ff',
      textLight: '#7ec8e3',
    },
    matchedDirectorIds: ['nolan', 'chazelle', 'wkw'],
    matchScores: { nolan: 0.8, chazelle: 0.72, wkw: 0.68 },
    stylePrompt:
      'Pandora ocean bioluminescent aesthetic, alien marine ecosystem, cool blue cyan tones, dramatic lighting, monumental scale, photorealistic 3D render, ethereal glow',
    negativePrompt: 'low quality, cartoon, flat lighting, earth setting',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 700,
    status: 'active',
    featured: false,
    approved: true,
  },
  {
    id: 'jurassic-rebirth-2026',
    title: '侏罗纪世界：重生',
    enTitle: 'Jurassic World: Rebirth',
    director: '加雷斯·爱德华兹',
    releaseDate: '2026-06-13',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hWXdgXm1hfnuSIOtWGinBe1GrdS.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/fncHijpWjitFBmj7SX5z148XEhP.jpg',
    heatScore: 79,
    boxOffice: 80000000,
    boxOfficeRank: 4,
    socialHeat: 'high',
    socialMentions: 5200000,
    trendingPeriod: '2026.06',
    lastUpdated: '2026-06-24',
    visualStyle: '写实派怪兽美学·丛林战争',
    styleKeywords: ['怪兽', '丛林', '写实', '战争', '恐龙'],
    signatureScenes: ['雇佣兵丛林战场', '恐龙融入人类生态'],
    iconicQuotes: ['生命会找到出路', '恐龙不再是化石，它们是现在'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'low',
      contrast: 'high',
      compositionType: 'dynamic',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'grainy',
    },
    colors: {
      primary: '#2d5016',
      secondary: '#1a1a0a',
      accent: '#8b0000',
      bg: '#0d1a0d',
      text: '#d4d4c4',
      textLight: '#8a8a7a',
    },
    matchedDirectorIds: ['nolan', 'kurosawa', 'jia'],
    matchScores: { nolan: 0.78, kurosawa: 0.7, jia: 0.55 },
    stylePrompt:
      'Realistic monster aesthetic, jungle warfare, desaturated cool tones, high contrast, dramatic lighting, monumental dinosaurs, gritty texture, cinematic',
    negativePrompt: 'cartoon, bright colors, cute, flat lighting',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 800,
    status: 'active',
    featured: false,
    approved: true,
  },
  {
    id: 'nolan-untitled-2026',
    title: '诺兰未定名新片',
    enTitle: 'Nolan Untitled',
    director: '克里斯托弗·诺兰',
    releaseDate: '2026-07-17',
    posterUrl: '',
    backdropUrl: '',
    heatScore: 75,
    boxOffice: 0,
    boxOfficeRank: 0,
    socialHeat: 'high',
    socialMentions: 4800000,
    trendingPeriod: '2026.07 (即将上映)',
    lastUpdated: '2026-06-24',
    visualStyle: 'IMAX胶片·时间结构叙事',
    styleKeywords: ['IMAX', '胶片', '时间结构', '谍战', '实拍'],
    signatureScenes: ['待上映'],
    iconicQuotes: ['时间是最伟大的导演'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'low',
      contrast: 'high',
      compositionType: 'symmetric',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'grainy',
    },
    colors: {
      primary: '#6a8caf',
      secondary: '#9db4c0',
      accent: '#c9b458',
      bg: '#1a2332',
      text: '#e8e0c8',
      textLight: '#b8a878',
    },
    matchedDirectorIds: ['nolan', 'kurosawa', 'coppola'],
    matchScores: { nolan: 0.95, kurosawa: 0.6, coppola: 0.55 },
    stylePrompt:
      'IMAX film aesthetic, Christopher Nolan style, cool desaturated tones, high contrast, dramatic lighting, monumental scale, time-bending narrative, gritty film texture',
    negativePrompt: 'bright colors, cartoon, warm tones, flat lighting',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 900,
    status: 'upcoming',
    featured: false,
    approved: true,
  },
  {
    id: 'wandering-earth3-2026',
    title: '流浪地球3',
    enTitle: 'The Wandering Earth 3',
    director: '郭帆',
    releaseDate: '2026-02-07',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7pNAki9AIaJGhNFOs8ePTFI0lDc.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/cCzMePim8EXRHExizmBhJC063Ju.jpg',
    heatScore: 72,
    boxOffice: 5200000000,
    boxOfficeRank: 5,
    socialHeat: 'medium',
    socialMentions: 3600000,
    trendingPeriod: '2026.02 - 2026.05',
    lastUpdated: '2026-06-24',
    visualStyle: '重工业科幻·地下城',
    styleKeywords: ['重工业', '科幻', '地下城', '硬核', '中国'],
    signatureScenes: ['太阳氦闪危机', '地下城实景'],
    iconicQuotes: ['道路千万条，安全第一条', '希望是这个时代像钻石一样珍贵的东西'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'low',
      contrast: 'high',
      compositionType: 'symmetric',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'grainy',
    },
    colors: {
      primary: '#3a5a8a',
      secondary: '#1a2a3a',
      accent: '#ff6b35',
      bg: '#0a0f1a',
      text: '#c8d0d8',
      textLight: '#8a9098',
    },
    matchedDirectorIds: ['nolan', 'kurosawa', 'chazelle'],
    matchScores: { nolan: 0.82, kurosawa: 0.65, chazelle: 0.5 },
    stylePrompt:
      'Heavy industrial sci-fi, underground city, cool blue steel tones, high contrast, dramatic lighting, monumental machinery, gritty texture, Chinese hard sci-fi',
    negativePrompt: 'bright colors, cartoon, fantasy, warm tones',
    fontFamily: "'Noto Sans SC', sans-serif",
    titleWeight: 800,
    status: 'active',
    featured: false,
    approved: true,
  },
  {
    id: 'fengshen3-2026',
    title: '封神第三部',
    enTitle: 'Creation of the Gods III',
    director: '乌尔善',
    releaseDate: '2026-07-01',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ny8A2v1pxD0TvKmbEE5f7BMhC4C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/jfUOhM0Xz4yOCWLFpdw1M1fft0V.jpg',
    heatScore: 68,
    boxOffice: 0,
    boxOfficeRank: 0,
    socialHeat: 'medium',
    socialMentions: 2800000,
    trendingPeriod: '2026.07 (即将上映)',
    lastUpdated: '2026-06-24',
    visualStyle: '中国神话史诗·神仙大战',
    styleKeywords: ['神话', '史诗', '神仙', '战争', '东方'],
    signatureScenes: ['诛仙阵神话奇观', '姬发与殷郊宿命对决'],
    iconicQuotes: ['天命不可违', '封神榜上，皆有定数'],
    styleDNA: {
      colorTemperature: 'warm',
      saturation: 'high',
      contrast: 'high',
      compositionType: 'symmetric',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'dynamic',
      texture: 'painterly',
    },
    colors: {
      primary: '#8b0000',
      secondary: '#2c0a0a',
      accent: '#ffd700',
      bg: '#1a0505',
      text: '#f0e0c0',
      textLight: '#c9a96e',
    },
    matchedDirectorIds: ['kurosawa', 'lee', 'miyazaki'],
    matchScores: { kurosawa: 0.85, lee: 0.72, miyazaki: 0.6 },
    stylePrompt:
      'Chinese mythology epic, gods warfare, warm red and gold tones, high saturation, dramatic lighting, monumental scale, painterly texture, oriental fantasy',
    negativePrompt: 'western fantasy, cartoon, modern city, flat lighting',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 900,
    status: 'upcoming',
    featured: false,
    approved: true,
  },
  {
    id: 'tron-ares-2026',
    title: '创：战神',
    enTitle: 'Tron: Ares',
    director: '约阿希姆·罗宁',
    releaseDate: '2026-05-23',
    posterUrl: 'https://image.tmdb.org/t/p/w500/t3DKqRvdaT1on8MRZCXXm4av9Cp.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/pUNfHmVqfwRdILhCkU8TdysVOXo.jpg',
    heatScore: 62,
    boxOffice: 35000000,
    boxOfficeRank: 8,
    socialHeat: 'medium',
    socialMentions: 1900000,
    trendingPeriod: '2026.05 - 2026.06',
    lastUpdated: '2026-06-24',
    visualStyle: '赛博朋克·电子网格美学',
    styleKeywords: ['赛博朋克', '霓虹', '电子', '网格', '数字世界'],
    signatureScenes: ['数字世界穿越', '霓虹光效对决'],
    iconicQuotes: ['在网格之中，一切皆有可能'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'high',
      contrast: 'high',
      compositionType: 'asymmetric',
      lightingType: 'low-key',
      scale: 'medium',
      pace: 'dynamic',
      texture: 'digital',
    },
    colors: {
      primary: '#00ffff',
      secondary: '#ff00ff',
      accent: '#00ff00',
      bg: '#0a0a1a',
      text: '#e0e0ff',
      textLight: '#8080a0',
    },
    matchedDirectorIds: ['wkw', 'chazelle', 'nolan'],
    matchScores: { wkw: 0.78, chazelle: 0.7, nolan: 0.65 },
    stylePrompt:
      'Cyberpunk electronic grid aesthetic, neon light effects, digital world, cool cyan and magenta tones, high contrast, low-key lighting, digital texture, futuristic',
    negativePrompt: 'natural, warm tones, organic, film grain, vintage',
    fontFamily: "'Noto Sans SC', sans-serif",
    titleWeight: 700,
    status: 'active',
    featured: false,
    approved: true,
  },
  {
    id: 'moon-base-2026',
    title: '月球基地',
    enTitle: 'Moon Base',
    director: '待定',
    releaseDate: '2026-07-15',
    posterUrl: '',
    backdropUrl: '',
    heatScore: 55,
    boxOffice: 0,
    boxOfficeRank: 0,
    socialHeat: 'rising',
    socialMentions: 950000,
    trendingPeriod: '2026.07 (即将上映)',
    lastUpdated: '2026-06-24',
    visualStyle: '近未来写实科幻',
    styleKeywords: ['月球', '近未来', '写实', '救援', '太空'],
    signatureScenes: ['30天极限救援', '太空碎片隔绝地球与月球'],
    iconicQuotes: ['回家，是最远的旅程'],
    styleDNA: {
      colorTemperature: 'cool',
      saturation: 'low',
      contrast: 'medium',
      compositionType: 'asymmetric',
      lightingType: 'natural',
      scale: 'monumental',
      pace: 'static',
      texture: 'smooth',
    },
    colors: {
      primary: '#a0a0b0',
      secondary: '#2a2a3a',
      accent: '#4a90d9',
      bg: '#0a0a14',
      text: '#d0d0e0',
      textLight: '#9090a0',
    },
    matchedDirectorIds: ['nolan', 'jia', 'coppola'],
    matchScores: { nolan: 0.72, jia: 0.65, coppola: 0.55 },
    stylePrompt:
      'Near-future realistic sci-fi, lunar base, cool gray tones, low saturation, natural lighting, monumental space, smooth texture, isolation atmosphere',
    negativePrompt: 'fantasy, bright colors, cartoon, warm tones',
    fontFamily: "'Noto Sans SC', sans-serif",
    titleWeight: 700,
    status: 'upcoming',
    featured: false,
    approved: true,
  },
  {
    id: 'oppenheimer-2023',
    title: '奥本海默',
    enTitle: 'Oppenheimer',
    director: '克里斯托弗·诺兰',
    releaseDate: '2023-07-21',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg',
    heatScore: 58,
    boxOffice: 9500000000,
    boxOfficeRank: 6,
    socialHeat: 'medium',
    socialMentions: 1500000,
    trendingPeriod: '2023.07 - 2024.03',
    lastUpdated: '2026-06-24',
    visualStyle: 'IMAX胶片·历史传记',
    styleKeywords: ['IMAX', '胶片', '历史', '传记', '核爆'],
    signatureScenes: ['三位一体核爆试验', '奥本海默听证会'],
    iconicQuotes: ['我成了死神，世界的毁灭者', '我们是否做过原子弹该做的事'],
    styleDNA: {
      colorTemperature: 'warm',
      saturation: 'low',
      contrast: 'high',
      compositionType: 'centered',
      lightingType: 'dramatic',
      scale: 'monumental',
      pace: 'static',
      texture: 'grainy',
    },
    colors: {
      primary: '#c9a45c',
      secondary: '#1a1a0a',
      accent: '#ff4500',
      bg: '#0f0a05',
      text: '#e8d5b7',
      textLight: '#b8a878',
    },
    matchedDirectorIds: ['nolan', 'coppola', 'kurosawa'],
    matchScores: { nolan: 0.92, coppola: 0.68, kurosawa: 0.6 },
    stylePrompt:
      'IMAX film biographic aesthetic, Christopher Nolan style, warm desaturated tones, high contrast, dramatic lighting, monumental scale, gritty film texture, historical drama',
    negativePrompt: 'cartoon, bright colors, fantasy, modern UI',
    fontFamily: "'Noto Serif SC', serif",
    titleWeight: 900,
    status: 'archived',
    featured: false,
    approved: true,
  },
];
